### ISSUE TITLE
Cannot set the port from the beginning...

### ISSUE THREAD

**Issue by qtw1998** [philnash/ngrok-for-vscode#14]
![image](https://user-images.githubusercontent.com/34357479/79995046-49e1c280-84e9-11ea-98f5-8b182f43220a.png)

**Comment by philnash** [comment]
Oh no!

When you tried to open a port for the first time, did you see a message that said it was downloading ngrok?

Also, can you open the developer tools (Help -> Toggle Developer Tools) and see if there are any logs from the extension too.

**Comment by MichaelCduBois** [comment]
Believe this issue is the same that I am having. I am on Windows 10, and when I execute the `ngrok: start` command, I get the following error:

```
ERR spawn ./ngrok.exe ENOENT: Error: spawn ./ngrok.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by philnash** [comment]
Thanks @MichaelCduBois. I don't have a Windows machine, so this is a little hard for me to test.

When you first run `ngrok: start` the extension should try to download the ngrok executable and store it within the extension. Once it has done that it then uses that executable.

On Windows it seems like it either fails to download or thinks it already has the executable downloaded. Do you see the message ["ngrok binary is already downloaded"](https://github.com/philnash/ngrok-for-vscode/blob/master/src/ngrok/index.ts#L233) in the developer tools console when you try to run the extension after installing the extension?

I'll see what I can do about getting a Windows 10 VM to see if I can reproduce this myself.

**Comment by MichaelCduBois** [comment]
@philnash I confirmed `ngrok binary is already downloaded` in the developer tools console. I have removed the executable from my system, in order to troubleshoot further.

Fresh install of the extension replicates my comment above.

**Comment by philnash** [comment]
OK, I think it turned out that I'd fixed this in version 1.2.0 and then broke it in version 1.3.0 when moving to a bundled package with webpack.

But I've just released [version 1.4.0](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) and I think it is fixed again (it worked on the Windows 10 testing VM I downloaded).

Please give it a try and let me know if this is sorted.

**Comment by MichaelCduBois** [comment]
Upon testing [version 1.4.0](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) via the marketplace, I can confirmed that the issue has been fixed.

![Fixed](https://user-images.githubusercontent.com/39778093/81702618-c43a9e00-9428-11ea-81b6-2cf324a164dc.png)

**Comment by philnash** [comment]
Thanks for testing @MichaelCduBois! 

I'm going to close this issue for now, if anyone else is still experiencing this, please feel free to re-open and provide as many details as possible.

Thanks!
