### ISSUE TITLE
Accept relative/default config paths

### ISSUE THREAD

**Issue by jagoe** [philnash/ngrok-for-vscode#15]
Currently, the config path has to be absolute. If I want to use ngrok for several projects that means adding a (likely very similar) path for each project.

Instead, I'd like to either set a global config path of, say, './.ngrok.yaml' and have it be resolved per workspace to `${rootPath}/.ngrok.yaml` or have a built-in default for a config file in the workspace root. Another alternative would be to parse variables like `${rootPath}`, which would also allow for a global setting.

I wouldn't mind contributing a PR once one or more preferred solutions have been decided on.

**Comment by philnash** [comment]
Hey @jagoe,

Thanks for bringing this up. Interesting idea.

Can I ask why you would want to use more than one config, or a different config per project?

You can set [different named tunnels within the single ngrok config file](https://ngrok.com/docs#tunnel-definitions) that define how a tunnel should behave. Would that not work for you, or do you have a completely different workflow in mind?

Cheers!

**Comment by jagoe** [comment]
Hey, thanks for the quick reply!

My reasoning is that this way several developers working on the same code base can get started with demoing, reviews or testing more quickly by just installing ngrok and the extension and having no to little configuration by just sharing the same config file in the code base.
I guess the same goal can be achieved using make, npm or similar tools, so the added convenience is admittedly not that big.

**Comment by philnash** [comment]
Good news to start with here. Installing the extension actually installs ngrok.

But I’m still unclear on how sharing config files will help. Firstly, the config file is the place to store your auth token, which shouldn’t be checked into source control. Secondly, if you use named sub domains then you may end up with tunnel clashes.

I genuinely see ngrok config as something personal to a developer, rather than set on a per project basis.

**Comment by jagoe** [comment]
Alright, I get that. I'm pretty new to ngrok (actually read about it the first time in your article), so I may have misunderstood how it's supposed to be used.
I'll still play around a bit and see if I can make my general idea work for the purposes I mentioned, just for fun :)

I'll go ahead and close the issue then.

**Comment by philnash** [comment]
I'm pleased I could introduce you to ngrok! Hopefully both ngrok and this extension are useful to you.

Let me know if this idea still appeals to you after using the tools for a while.
