### ISSUE TITLE
Feature request: start/stop with arguments from other extensions

### ISSUE THREAD

**Issue by inercia** [philnash/ngrok-for-vscode#21]
I was wondering if it could be possible to invoke the `start`/`stop` commands provided by this extension _with arguments_ from other extensions.

I'm currently developing an [extension for starting local Kubernetes clusters with the help of K3D](https://github.com/inercia/vscode-k3d/). I think `vscode.commands.executeCommand("ngrok-for-vscode.start")` could be used for invoking the `start` command, but I would like to pass the local IP and port as arguments. I was wondering if this could be possible now or if it could be possible to add this feature in the future...

**Comment by philnash** [comment]
Sorry for the delay in getting back to you on this. I think #23 should implement this. I don't know if you can try it out yourself or if you just need me to merge and release a version to test this with.

Let me know what you think.

**Comment by philnash** [comment]
I have merged #23, so I consider this closed. Please let me know if it works from another extension!
