### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by pipaliyachirag** [philnash/ngrok-for-vscode#22]
![image](https://user-images.githubusercontent.com/35637220/103418498-f023b300-4bb4-11eb-87c9-73a87cfceb97.png)
some issue with extension.

**Comment by philnash** [comment]
Hey, the only thing I changed recently was to add the version of the ngrok executable. I guess that maybe doesn't work on Windows. I've pushed a new version that handles that failure, please try updating to version 1.8.3 and let me know if it works again.

Thanks!

**Comment by pipaliyachirag** [comment]
worked thanks 😁

**Comment by macx** [comment]
@pipaliyachirag Which theme do you use?
