### ISSUE TITLE
Way to Start Multiple Tunnels Simultaneously

### ISSUE THREAD

**Issue by anthonygualandri** [philnash/ngrok-for-vscode#30]
I'm getting an error in the extension when I try and start a tunnel when another tunnel is running. Is there a way to start multiple tunnels at once with the extension?

**Comment by philnash** [comment]
Hmm, I am able to start multiple tunnels, see the screenshot below:

<img width="344" alt="multiplengrok" src="https://user-images.githubusercontent.com/31462/159850526-693f2536-8529-48b2-b1d9-029c604fb0b7.png">

Do you have an ngrok account and have you set the authtoken in your ngrok config (which you can do through the plugin too)?

**Comment by philnash** [comment]
So you’re trying to start two separate ngrok processes, but the [ngrok pricing page](https://ngrok.com/pricing) says that free and basic accounts can only run one process at a time. 

So, to run two instances of ngrok in your two Codespaces you’ll either need to upgrade to pro (or maybe open two ngrok accounts?).

This isn’t something I can control within this plugin though, I’m afraid.

**Comment by philnash** [comment]
Hey @anthonygualandri, did my last comment answer your question?

**Comment by philnash** [comment]
I'm going to close this issue as there has been no response. Please feel free to reopen if there's more to discuss.
