### ISSUE TITLE
There was an error starting your tunnel.

### ISSUE THREAD

**Issue by thomas-brandeho** [philnash/ngrok-for-vscode#4]
Hello,

just tried your extension which seemed nice, but I can't get it to run.

What I do : 

Ctrl+Shift+P
ngrok: start
Fill port number : 8024 for example.

A notification show a message : "There was an error starting your tunnel"

Sorry that I can't give more informations. 
Do extensions give log somewhere with more explanations as to what happened?

**Comment by philnash** [comment]
Hey @thomas-brandeho, thanks for trying the extension!

What operating system are you using? You can also check the developer tools for logs, see [this answer for how](https://stackoverflow.com/questions/44188262/where-are-the-vscode-error-logs-for-extensions).

**Comment by thomas-brandeho** [comment]
Thanks for the reply.
My system is Ubuntu 19.10.
VSCode is 1.44.1.

I will check the developer tools and will let you know if I find a clue about what is happening.

**Comment by philnash** [comment]
I think I might have bundled the Mac binary for ngrok in the package.

Currently exploring postinstall scripts, or a way to download the correct binary for the system.

**Comment by thomas-brandeho** [comment]
Here are the log when trying to start a tunnel : 
[ngrok_start_error.log](https://github.com/philnash/ngrok-for-vscode/files/4481821/ngrok_start_error.log)

**Comment by philnash** [comment]
Could you try installing and using [version 1.2.0](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) please? It should be working now.

**Comment by thomas-brandeho** [comment]
Yes it's working.
Thank you very much.

**Comment by philnash** [comment]
Awesome, thank you!

**Comment by gtichess** [comment]
> Hello,
> 
> just tried your extension which seemed nice, but I can't get it to run.
> 
> What I do :
> 
> Ctrl+Shift+P ngrok: start Fill port number : 8024 for example.
> 
> A notification show a message : "There was an error starting your tunnel"
> 
> Sorry that I can't give more informations. Do extensions give log somewhere with more explanations as to what happened?

**Comment by gtichess** [comment]
I am experiencing this same problem. Ctrl+Shift+P --> run ngrok --> 3000


![image](https://github.com/philnash/ngrok-for-vscode/assets/146866641/4ee88b2a-de19-4819-ac4b-7592b86c9ccf)

https://github.com/philnash/ngrok-for-vscode/issues/4#issue-600268249


My system is Windows 10Pro

Thanks

**Comment by philnash** [comment]
Hi @gtichess, can you [check the developer tools](https://stackoverflow.com/questions/44188262/where-are-the-vscode-error-logs-for-extensions) and see if anything is logged about the error.
