### ISSUE TITLE
Update to ngrok3?

### ISSUE THREAD

**Issue by TrueFundsTech** [philnash/ngrok-for-vscode#57]
This extension uses ngrok version 2 which will be phased out of use on January 15th, 2024.

Ngrok now recommends using version 3.2 as the minimum version.

Is there any plan to update this extension to use ngrok version 3.2?

**Comment by justngrok** [comment]
Adding some additional information:

ngrok requires that an Authtoken is installed, so set authtoken is now a requirement 
ngrok also requires that if you are using a Free plan account, that version 3.2 Agent or higher is required.
https://ngrok.com/docs/agent/version-support-policy/

Note: Paid accounts are still able to use version 2.X of the ngrok Agent.

This extension uses the ngrok npm package version 4.3.2, which wraps the ngrok v2.X Agent.
Version 5 of the npm package supports the v3.X agent.
https://www.npmjs.com/package/ngrok?activeTab=readme
> This project is the Node.js wrapper for the [ngrok client](https://ngrok.com/download). Version 5 of this project uses ngrok client version 3. For ngrok client version 2, check out version 4.

The default ngrok.yml path in version 3 has also changed.

**Comment by TrueFundsTech** [comment]
> Adding some additional information:
> 
> ngrok requires that an Authtoken is installed, so set authtoken is now a requirement ngrok also requires that if you are using a Free plan account, that version 3.2 Agent or higher is required. https://ngrok.com/docs/agent/version-support-policy/
> 
> Note: Paid accounts are still able to use version 2.X of the ngrok Agent.
> 
> This extension uses the ngrok npm package version 4.3.2, which wraps the ngrok v2.X Agent. Version 5 of the npm package supports the v3.X agent. https://www.npmjs.com/package/ngrok?activeTab=readme
> 
> > This project is the Node.js wrapper for the [ngrok client](https://ngrok.com/download). Version 5 of this project uses ngrok client version 3. For ngrok client version 2, check out version 4.
> 
> The default ngrok.yml path in version 3 has also changed.

Thank you for the reply, I will check this out, but for now VSCode's inbuilt port forwarding solves my purpose.
