### ISSUE TITLE
Tunnel doesn't start, no feedback

### ISSUE THREAD

**Issue by chuck-wood** [philnash/ngrok-for-vscode#6]
Hi Phil! Thanks for making this extension available -- I'm a fan of ngrok _and_ VSC, so putting'em together seems like a great idea.

I just installed the extension and I'm afraid when I run `ngrok: start` I get absolutely no indication of anything happening. The command palette just goes away and that's it.

Versions:
* VSC: 1.44.1
* ngrok: 2.3.35
* ngrok for VSCode: 1.1.0

I do have a tunnel defined in my ngrok config file and have given the extension the path to the config file. I've confirmed that I can run the tunnel from the command line. I do get error messages if I put a malformed path to the config file. Running `ngrok: dashboard` from the command palette gives me an error that ngrok isn't running.

Any ideas?

**Comment by philnash** [comment]
Hi @chuck-wood, I'm guessing you're on Windows or Linux? I think that I've messed up and bundled the Mac binary for ngrok with the extension so it only works on Macs right now. I've raised issue #7 to cover this.

Hopefully we can git this sorted shortly, thanks for trying out the extension!

**Comment by chuck-wood** [comment]
Windows indeed, sorry for leaving that out. Thanks for the quick reply!

**Comment by philnash** [comment]
Could you try installing and using [version 1.2.0](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) please? It should be working now.

**Comment by chuck-wood** [comment]
Okay, I updated by reloading VSCode. I ran `ngrok: start` and it popped up a toast saying that it was downloading the ngrok binary (on a side note, I already have it installed so it would be cool if there was an option to point at an existing binary). After a bit I ran `ngrok: start` again, it prompted me to select a profile, and it ran successfully. Thanks for the quick turnaround!

**Comment by philnash** [comment]
Thanks for testing @chuck-wood, glad it works!

The binary download is just how the ngrok npm module works right now. I agree, it's worth seeing if you can point it at an existing installation, but this was definitely the most straightforward way to get it to work to start with.

Let me know if you have any other feature requests!

**Comment by chuck-wood** [comment]
Ah I see. No worries, it's great to make use of tools to build things quickly. Cheers!
