### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Michsior14** [philnash/ngrok-for-vscode#9]
It would be nice to have CI configured for the project using Actions either Azure Pipelines, so there is automating testing and building in place.

Example configurations: https://code.visualstudio.com/api/working-with-extensions/continuous-integration

Of course I can offer my help.

**Comment by philnash** [comment]
It's a good idea (once I've written some tests).

I will probably try to set this up myself. I haven't worked with Azure Pipelines before, so this would be a good learning experience. I'll definitely call on you if I get stuck and you don't mind!

**Comment by philnash** [comment]
Decided on a GitHub Actions workflow. Turned out straightforward to set up. Now adding tests.
